events {}

http {
    log_format debug '$remote_addr - $host [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" $upstream_addr $request_time';

    access_log /var/log/nginx/access.log debug;

    upstream backend {
        ip_hash;
        # least_conn;
        # # ip_hash;
        # # # least_conn;
        # Algoritmo padrão (Round Robin)
        server web1:5000;
        server web2:5000;
        server web3:5000;
        # Para testar outros modos:
        # # # # # # least_conn;
        # # # # # # ip_hash;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}
