events {}

http {
    log_format debug '$remote_addr - $host [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" upstream=$upstream_addr '
                     'backend_name=$upstream_http_x_backend_name '
                     'request_time=$request_time';

    access_log /var/log/nginx/access.log debug;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
    set_real_ip_from 0.0.0.0/0;

    upstream backend {
        ip_hash;
        # least_conn;
        # # # ip_hash;
        # # # # least_conn;
        # # # # # # ip_hash;
        # # # # # # # least_conn;
        # # # # # # # # # ip_hash;
        # # # # # # # # # # least_conn;
        server web1:5000;
        server web2:5000;
        server web3:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;

            # 🔹 Garante que Nginx preserve headers vindos do backend
            proxy_pass_request_headers on;
            proxy_pass_request_body on;

            # 🔹 Permite que o Nginx leia os headers de resposta do backend
            proxy_pass_header X-Backend-Name;
            proxy_hide_header X-Backend-Name;
        }
    }
}
